package:
  name: cyvlfeat
  version: {{ CONDACI_VERSION }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - cython >0.23
    - vlfeat 0.9.*
    - msinttypes r26  # [win]

  run:
    - python
    - vlfeat 0.9.*
    - numpy >=1.10

test:
  requires:
    - nose
    - coverage

  imports:
    - cyvlfeat.slic.slic 
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans
    - cyvlfeat.generic.generic

  commands:
    - nosetests cyvlfeat -v --cover-package=cyvlfeat

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
