package:
  name: cyvlfeat
  version: {{ CONDACI_VERSION }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<1.12
    - cython >=0.24,<0.25
    - vlfeat 0.9.*
    - msinttypes r26  # [win]

  run:
    - python
    - vlfeat 0.9.*
    - numpy >=1.10,<1.12

test:
  requires:
    - nose
    - coverage

  imports:
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans

  commands:
    - nosetests cyvlfeat -v --cover-package=cyvlfeat

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
